config/routes.rb
Rails.application.routes.draw do
  
  root 'rooms#main'
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    resources :rooms
    devise_for :users

    get '/secret/:id' => 'rooms#secret'
    post '/passcheck/:id' => 'rooms#passCheck'
    post '/search' => 'rooms#search'

    delete '/roomquit' => 'rooms#roomquit'

    get '/chat' => 'chat#index'
    get 'help' => 'rooms#help', as: :help
    post '/startGame' => 'rooms#startGame', as: :startGame

    get '/result/:id/:winner_id' => 'rooms#result', as: :result
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_secure_password
  validates :title, presence: true
  has_many :players, :dependent => :destroy
  has_many :users, through: :players

  belongs_to :question
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: :main
  before_action :exit_chk, except: [:show, :create, :edit, :update, :main, :startGame, :result]

  def main

  end

  def index
    @room = Room.all.reverse
  end

  def new
    @room = Room.new
  end

  def create
    question_id =  params.require(:room).permit(:question)['question'].to_i
    question = Question.find(question_id)

    room = question.rooms.new(rooms_params)
    room.nowPlaying = false

    if room.isSecret == false
      room.password = "ThisIsaDummy"
    end

    if room.save
      room.players.create(user_id: current_user.id, isMaster: true, isReady: true)
      session[:lastroom] = room.id
      redirect_to room
    else
      redirect_to new_room_path, flash: {alert: "에러 발생! 무언가 잘못되었어요"}
    end

  end

  def show
    @room = Room.find(params[:id])

    if (@room.nowPlaying == true) && (!current_user.player)
      redirect_to rooms_path, flash: {alert: "게임중인 방에는 들어갈 수 없어요"}
      return
    end

    if !current_user.player
      @room.players.create(user_id: current_user.id)
    end

    @user = Player.find_by_user_id(current_user.id)
    room_authenticate
    session[:lastroom] = @room.id

    @emitter = SocketIO::Emitter.new(
      redis: Redis.new(
        :host => '34.67.110.223',
        # :host => 'localhost',
        :port => '6379'
      )
    )

    @players = @room.players.map {|m| m.user.id}
  end

  def edit
    if (current_user.room.id.to_s == params[:id] ) && (current_user.player.isMaster)
      @room = Room.find(params[:id])
    else
      redirect_to current_user.room, flash: {alert: "방장만 방 정보를 수정할 수 있어요"}
    end
  end

  def update
    room = Room.find(params[:id])
    room.update(rooms_params)
    question_id =  params.require(:room).permit(:question)['question'].to_i
    question = Question.find(question_id)
    room.update(question: question)

    if room.save
      session[:lastroom] = room.id
      redirect_to room
    else
      redirect_to new_room_path, flash: {alert: "에러 발생! 무언가 잘못되었어요"}
    end
  end

  def destroy

  end

  def secret
    @room = Room.find(params[:id])
  end

  def passCheck
    @room = Room.find(params[:id])
    chk = @room.authenticate(params[:roomPassword])
    if chk
      session[:lastroom] = @room.id
      redirect_to room_path(@room)
    else
      redirect_to '/secret/' + @room.id.to_s, flash: {alert: "비밀번호가 다릅니다!"}
    end
  end

  def search
    begin
      room = Room.find(params[:q])
    rescue ActiveRecord::RecordNotFound
      redirect_to rooms_path, flash: {alert: "없는 번호입니다!"}
    else
      redirect_to room
    end
  end

  def roomquit
    player = current_user.player
    room = player.room
    num_person = room.players.count

    if num_person == 1
      room.destroy
      player.destroy
      redirect_to rooms_path
      return
    end

    if player.isMaster == true
      next_user = Room.find(room.id).players.second
      next_user.update(isMaster: true)
    end
    player.destroy



    redirect_to rooms_path
  end

  def help

  end

  def startGame
    room = current_user.room
    # ------------ 솔로 플레잉 방지 (디버깅 시 오프)
    if room.players.size == 1
      redirect_to room, flash: {alert: "혼자서는 게임할 수 없어요!"}
      return
    end
    # -------------------------------
    stat = !room.nowPlaying
    room.update(nowPlaying: stat)
    redirect_to room
  end

  def reloadGame
    room = current_user.room
    redirect_to room
  end

  def result
    if current_user.player.isMaster == true
      current_user.room.update(nowPlaying: false)
    end
    @room = params[:id]
    @winner = User.find(params[:winner_id])
  end

  private
  def rooms_params
    params.require(:room).permit(:title, :questionNumber, :limitTime, :isSecret, :password)
  end

  def room_authenticate
    if (@room.isSecret == true) and (session[:lastroom] != @room.id)
      redirect_to '/secret/' + params[:id]
      return
    end

  end

  def exit_chk
    if current_user.room && current_user.player
      if current_user.room.players.count <= 1 # 혼자 있었으면
        current_user.room.destroy
      else
        if current_user.player.isMaster == true
          next_user = Room.find(current_user.room.id).players.second
          next_user.update(isMaster: true)
        end
        current_user.player.destroy
      end
    end
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: @room, local: true) do  |form| %>

  <div class="form-group">
    <%= form.label :title, t('rooms.form.text1') %>
    <%= form.text_field :title, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :question, t('rooms.form.text2') %>
    <%= collection_select :room, :question, Question.all, :id, :title, {}, html_options={class: "form-control"} %>
  </div>

  <div class="form-group row">
    <div class="col-sm-6">
      <%= form.label :count, t('rooms.form.text3') %>
      <%= form.number_field :questionNumber, value:15, max:30, min:5, class:"form-control"%>
    </div>
    <div class="col-sm-6">
      <%= label_tag :limitTime, t('rooms.form.text4') %>
      <%= form.number_field :limitTime, value: 60, max:300, min:20, class:"form-control"%>
    </div>
  </div>

  <div class="form-group">
    <div class="custom-control custom-switch">
      <%= form.check_box :isSecret, class: "custom-control-input"%>
      <%= form.label :isSecret, t('rooms.form.text5'),id: :isSecret, onclick: "openPass()", class:"custom-control-label" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :password, t('rooms.form.text6') %>
    <%= form.password_field :password, class:"form-control", disabled: true%>
  </div>

  <div class="form-group">
    <%= form.submit t('rooms.form.text7'), class:"btn btn-secondary float-right margin-10", data: { turbolinks: false } %>
  </div>

  <div class="form-group">
    <%= form.submit t('rooms.form.text8'), class:"btn btn-outline-secondary float-left margin-10" %>
  </div>
<% end %>

app/views/rooms/_playingroom.html.erb
<!--<p hidden id="ViewTimer"></p>-->
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js" ></script>-->
<div class="row" style="height: 50px"></div>
<h1>#<%= @room.id %> / <%= @room.title %></h1>
<p><%= @room.question.title %></p>
<hr>
<h5><%= @room.question.description %></h5>
<hr>
<p><%= t('rooms.playingRoom.text1') %> : <%= @room.questionNumber %></p>
<p><%= t('rooms.playingRoom.text2') %> : <%= @room.limitTime %></p>
<hr>
<button id="startButton" class="form-control btn btn-danger" onClick="startButtonClick()"><%= t('rooms.playingRoom.text3') %></button><br />
<button id="unmuteButton" class="form-control btn btn" ><%= t('rooms.playingRoom.text4') %></button>
<br />
<hr>
<div id="box" class="container overflow-auto" style="height: 300px">
  <div id="messages" class="alert alert-secondary" style="text-decoration: underline; overflow: auto;">
  </div>
</div>
<div class="margin-s10"></div>

<form onsubmit="return false">
  <div class="form-group">
    <input type="text" id="text" class="form-control form-control-lg margin-top-10"  placeholder= <%= t('rooms.playingRoom.text1') %>
    onkeydown = "if (event.keyCode == 13)
                        document.getElementById('sendButton').click()" >

  </div>
  <input type="button" id="sendButton" value="send" onclick="send()" class="form-control btn btn-dark">
</form>

<div class="row">
  <% @room.players.each do |player| %>
    <div class="col-sm-4 margin-top-10">
      <div class="card border-info overflow-auto">
        <div id="card" class="card-body">
          <h5 class="card-title"><%= player.user.nickName %></h5>
          <p id="<%= player.user.id %>" class="card-text float-right">0 Points</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div hidden>
  <div id="player"></div>
</div>

<script>
    var player;
    var nowSong;
    var stArr;
    var url;
    var timeLimit = "<%= @room.limitTime %>";
    var socket = io.connect("http://34.67.110.223:4000");
    var nick = "<%=current_user.nickName%>";
    var score = 0;
    var currentId = "<%=current_user.id%>";
    var players = "<%=@players%>";
    var res = players.replace(/[\[\] ]/g, "").replace(/[^0-9]/g, ",");
    var result = res.split(",");
    var move = document.getElementById("box");
    var questionInfo = "<%= @room.question.title %>";
    var questionLimit = parseInt("<%= @room.questionNumber %>");
    var roomId = "<%= @room.id %>";
    var keyword;
    var answer;
    var index;
    var finishArray = [];

    const lang = window.location.pathname.split('/')[1];

    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '360',
            width: '640',
            videoId: `${nowSong}`,
            playerVars: {
                //'start': stArr[0], // 여기 수정
                // 무한반복용 루프 설정도구. 복잡해서 뺐음
                'start': 1,
                'loop' : 1,
                'playlist': `${nowSong}`,
                //'end': parseInt(stArr[0]) + parseInt("<%= @room.limitTime %>")
                'end': 100
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange,
            }
        });
    }

    function onPlayerReady(event) {
        event.target.mute();
    }

    function onPlayerStateChange(event) {
        setTimeout(stopVideo, 4000);
    }
    function stopVideo() {
        player.unMute();
    }

    unmuteButton.addEventListener('click', function() {
        player.playVideo();
    });

    function sysMsg(text) {
        let sysInfo = document.createElement('div');
        sysInfo.classList.add('text-info');
        sysInfo.appendChild(document.createTextNode(text));
        messages.appendChild(sysInfo);
    }

    if(lang == "ko"){
      setTimeout(() => {
        sysMsg('[시스템메시지] : 3초 뒤에 시작됩니다.');
      }, 1000);

      setTimeout(() => {
        sysMsg('[시스템메시지] : 2초 뒤에 시작됩니다.');
      }, 2000);
      setTimeout(() => {
        sysMsg('[시스템메시지] : 1초 뒤에 시작됩니다.');
      }, 3000);

      setInterval(() => {
        timeLimit -= 1;
      }, 1000);
    }else{
      setTimeout(() => {
        sysMsg('[システムメッセージ] : 3秒後に始まります.');
      }, 1000);

      setTimeout(() => {
        sysMsg('[システムメッセージ] : 2秒後に始まります.');
      }, 2000);
      setTimeout(() => {
        sysMsg('[システムメッセージ] : 1秒後に始まります.');
      }, 3000);

      setInterval(() => {
        timeLimit -= 1;
      }, 1000);
    }
    

    window.addEventListener('beforeunload', (event) => {
      event.preventDefault();
      event.returnValue = '진짜 나감??';
    });

// Socket
    socket.emit('question',{
      questionInfo: questionInfo,
      roomId: roomId,
    });
    console.log(questionInfo);

    socket.emit('grating', {nick: nick, roomId: roomId});

    socket.on('grating', (data) => {
      var messages = document.getElementById('messages');
      var text;
      if(lang == "ko"){
        text = document.createTextNode(`${data}님이 입장하셨습니다.`);
        sysMsg(`${data}님이 입장하셨습니다!`);
      }else{
        text = document.createTextNode(`${data}様が入場しました.`);
        sysMsg(`${data}様が入場しました！`);
      }
    });

    const timer = setInterval(() => {
      index = parseInt(url.findIndex(i => i == nowSong));
      if(timeLimit < 0) {
        nowSong = url[index+1];
        setTimeout(() => {
            console.log(url[index]);
          player.loadVideoById({
            'videoId': url[index],
            'startSeconds': stArr[index],
            'endSeconds': parseInt(stArr[index]) + parseInt(timeLimit)
          });
        }, 4000);
        timeLimit = "<%= @room.limitTime %>";
        if(lang =="ko"){
          sysMsg(`제한시간이 초과되었습니다.`);
          setTimeout(() => {
            sysMsg('[시스템메시지] : 3초 뒤에 시작됩니다.');
            if(move.scrollHeight > 0) {
              move.scrollTop = move.scrollHeight;
            }//자동스크롤
          }, 1000);
          setTimeout(() => {
            sysMsg('[시스템메시지] : 2초 뒤에 시작됩니다.');
            if(move.scrollHeight > 0) {
              move.scrollTop = move.scrollHeight;
            }//자동스크롤
          }, 2000);
          setTimeout(() => {
            sysMsg('[시스템메시지] : 1초 뒤에 시작됩니다.');
            console.log('현재' + index);
            if(move.scrollHeight > 0) {
              move.scrollTop = move.scrollHeight;
            }//자동스크롤
          }, 3000);
        }else{
          sysMsg(`時間切れになりました.`);
          setTimeout(() => {
            sysMsg('[システムメッセージ] : 3秒後に始まります.');
            if(move.scrollHeight > 0) {
              move.scrollTop = move.scrollHeight;
            }//자동스크롤
          }, 1000);
          setTimeout(() => {
            sysMsg('[システムメッセージ] : 2秒後に始まります.');
            if(move.scrollHeight > 0) {
              move.scrollTop = move.scrollHeight;
            }//자동스크롤
          }, 2000);
          setTimeout(() => {
            sysMsg('[システムメッセージ] : 1秒後に始まります.');
            console.log('현재' + index);
            if(move.scrollHeight > 0) {
              move.scrollTop = move.scrollHeight;
            }//자동스크롤
          }, 3000);
        }
        
      }

      //시간초과되었을 때 다음으로 넘김
      if(index === questionLimit || index === stArr.length){
        function finish(){
          for(var i in result){
            var finishUser = document.getElementById(result[i]).innerHTML;
            var point = finishUser.split(" ")[0];
            finishArray.push({id: result[i], point: parseInt(point)});
          }
          var max = finishArray.reduce(function(prev, current) {
            return (prev.point > current.point) ? prev : current
          });
          if(lang == "ko"){
            alert("문제가 모두 끝났습니다!\n결과 창으로 이동합니다!");
          }else{
            alert("問題が終わりました！\n結果ページへ移動します！");
          }
          
          window.location.href = `/result/<%= @room.id %>/${max.id}`; // 우승자 id값
        }
        finish();

        clearInterval(timer);
      }//문제 다 풀면 리다이렉트
    }, 1000);

    function send() {
      var value = document.getElementById("text").value;
      var pi = url.findIndex(i => i == nowSong);
      socket.emit("sendUser", {
        value: value,
        nick: nick,
        id: currentId,
        i: pi,
        roomId: roomId,
        keyword: keyword,
        answer: answer
      });
      document.getElementById('text').value = null;
      //이벤트 발생하면 인풋태그 비우기
      var move = document.getElementById('box');
      if(move.scrollHeight > 0) {
        move.scrollTop = move.scrollHeight;
      }//자동스크롤

    }
    //채팅 전송 이벤트 발생
    socket.on("userInfo", (data) => {
      var messages = document.getElementById("messages");
      var text = document.createTextNode(`${data.nick} : ${data.value}`);
      messages.appendChild(text);
      messages.appendChild(document.createElement("br"));
      var move = document.getElementById('box');
      if(move.scrollHeight > 0) {
        move.scrollTop = move.scrollHeight;
      }//자동스크롤
      //채팅
      console.log(data.flag);
      if(data.flag === true){
        if(data.nick === nick) {
          document.getElementById(currentId).innerHTML = `${data.score} Points`;
        }else{
          var search = result.indexOf(data.id);
          document.getElementById(result[search]).innerHTML = `${data.score} Points`;
        }
        var pi = url.findIndex(i => i == nowSong);
        answer[pi] = 'YomiQuiZMaDeBYYOMIAndideA';
        keyword[pi] = {keyword:''};
        //스코어 변경
        sysMsg(`${data.nick}님 정답입니다!`);
        if(move.scrollHeight > 0) {
          move.scrollTop = move.scrollHeight;
        }//자동스크롤
      }
      //시스템메시지
    });

    ///초기 재생오류 해결
    setTimeout(() => {player.loadVideoById({
        'videoId': url[0],
        'startSeconds': stArr[0],
        'endSeconds': parseInt(stArr[0]) + parseInt(timeLimit)
    })},2000);

    //채팅 오갈때마다 검사
    async function socketFunction() {
      await new Promise(resolve => {
        socket.on('answer', (data) => {
          resolve(data);
          url = data.url;
          nowSong = data.url[0];
          stArr = data.startTime;
          keyword = data.keyword;
          answer = data.answer;
        });
      });
      player.loadVideoById({
        'videoId': url[0],
        'startSeconds': stArr[0],
        'endSeconds': parseInt(stArr[0]) + parseInt(timeLimit)
      });

    }

    document.addEventListener("DOMContentLoaded", socketFunction);
    document.addEventListener("DOMContentLoaded", () => {
      console.log("연결");
    });
    //시작할 시 문제정보 받음
    //더미버튼
    function startButtonClick() {
        var btn = document.getElementById("startButton");
        btn.style.display = "none";
    }

    //새로고침 방지

    function doNotReload(){
        if(    (event.ctrlKey == true && (event.keyCode == 78 || event.keyCode == 82))
            || (event.keyCode == 116) )
        {
            event.keyCode = 0;
            event.cancelBubble = true;
            event.returnValue = false;
            if(lang == "ko"){
              alert("게임중에는 새로고침을 하실 수 없어요");
            }else{
              alert('ゲーム中にはリロードできません');
            }
        }
    }
    document.onkeydown = doNotReload;
</script>

app/views/rooms/_waitroom.html.erb
<div class="row" style="height: 50px"></div>
<h1>#<%= @room.id %> / <%= @room.title %></h1>
<p><%= @room.question.title %></p>
<hr>
<h5><%= @room.question.description %></h5>
<hr>
<p><%= t('rooms.waitingroom.text1') %> : <%= @room.questionNumber %></p>
<p><%= t('rooms.waitingroom.text2') %> : <%= @room.limitTime %></p>

<% if @user.isMaster == true %>
  <div class="row">
    <%= link_to t('rooms.waitingroom.text3'), startGame_path, class: "btn btn-lg btn-secondary col-sm-5", method: :post, "data-turbolinks": false, "onClick": "start()" %>
    <div class="col-sm-2"></div>
    <%#= link_to t('rooms.waitingroom.text4'), edit_room_path, class: "btn btn-lg btn-outline-dark col-sm-3", method: :get %>
<!--    <div class="col-sm-1"></div>-->
    <%= link_to t('rooms.waitingroom.text5'), rooms_path, class: "btn btn-lg btn-outline-dark col-sm-5", method: :get %>
  </div>
<% else %>
  <div class="row">
    <%= link_to t('rooms.waitingroom.text5'), rooms_path, class: "btn btn-lg btn-outline-dark col-sm-12", method: :get %>
  </div>
<% end %>

<hr>
<div id="box" class="container overflow-auto" style="height: 300px">
  <div id="messages" class="alert alert-secondary" role="alert" style="text-decoration: underline; overflow: auto;">

  </div>
</div>
<div class="margin-s10"></div>

<form onsubmit="return false">
  <div class="form-group">
    <input type="text" id="text" class="form-control form-control-lg margin-top-10"  placeholder=<%= t('rooms.waitingroom.text6') %>
    onkeydown = "if (event.keyCode == 13)
                        document.getElementById('sendButton').click()" >

  </div>
  <input type="button" id="sendButton" value="send" onclick="send()" class="form-control btn btn-dark">
</form>

<div class="row" style="height: 50px"> </div>
<div class="row">
  <% @room.players.each do |player| %>
    <div class="col-sm-4 margin-top-10">
      <% if player.isMaster  %>
        <div class="card border-warning overflow-auto">
          <div class="card-body">
            <h5 class="card-title"><%= player.user.nickName %></h5>
            <p class="card-text"></p>
          </div>
        </div>
      <% else %>
        <div class="card border-info overflow-auto">
          <div class="card-body">
            <h5 class="card-title"><%= player.user.nickName %></h5>
            <p class="card-text"></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

<!--<p id="ViewTimer"></p>-->

<script>

    var socket = io.connect("http://34.67.110.223:4000");
    var SetTime = 60;		// 최초 설정 시간(기본 : 초)
    var roomId = `waiting${<%= @room.id %>}`;
    var nick = "<%=current_user.nickName%>";
    var currentId = "<%=current_user.id%>";
    var playingFlag = "<%= @room.nowPlaying %>";
    var move = document.getElementById("box");

    const lang = window.location.pathname.split('/')[1];

    function send() {
      var value = document.getElementById("text").value;
      socket.emit("sendUserWaiting", {
        value: value,
        nick: nick,
        roomId: roomId
      });
      document.getElementById('text').value = null;
      //이벤트 발생하면 인풋태그 비우기
      var move = document.getElementById('box');
      if(move.scrollHeight > 0) {
        move.scrollTop = move.scrollHeight;
      }//자동스크롤
    }

    socket.emit('joinRoom', {roomId: roomId, nick: nick});

    socket.on('joinRoom', (data) => {
      var messages = document.getElementById("messages");
      var text;
      if(lang == "ko"){
        text = document.createTextNode(`${data}님이 입장하셨습니다.`);
      }else{
        text = document.createTextNode(`${data}様が入場しました.`);
      }
      
      messages.appendChild(text);
      messages.appendChild(document.createElement("br"));
      if(move.scrollHeight > 0) {
          move.scrollTop = move.scrollHeight;
      }//자동스크롤
    });

    socket.on('chat', (data) => {
      var messages = document.getElementById("messages");
      var text = document.createTextNode(`${data.nick} : ${data.value}`);
      messages.appendChild(text);
      messages.appendChild(document.createElement("br"));
      if(move.scrollHeight > 0) {
          move.scrollTop = move.scrollHeight;
      }//자동스크롤
    });

    function start(){
      socket.emit('playing', {
        roomId: roomId
      });
    }

    socket.on('playing', (data) => {
      console.log("Here!");
      setTimeout("history.go(0)", 300);
    });


</script>

app/views/rooms/edit.html.erb
<div class="container">
  <div class="row" style="height: 50px"></div>
  <h1><%= t('rooms.edit.text1') %></h1>
  <p><%= t('rooms.edit.text2') %></p>
  <div class="row" style="height: 50px"></div>
  <div class="alert alert-danger" role="alert">
    <%= t('rooms.edit.text3') %>
  </div>
  <%= render 'form' %>
</div>

app/views/rooms/help.html.erb
<div class="container">
  <div class="row" style="height: 50px"></div>
  <h1><%= t('rooms.help.text_help') %></h1>
  <p><%= t('rooms.help.text1') %></p>

  <hr>
  <h3><%= t('rooms.help.text2') %></h3>
  <p><a href="https://github.com/YMGYM">YMGYM(요미)</a>, <a href="https://github.com/idea7654">Idea</a></p>
  <br />
  <h4><%= t('rooms.help.text3') %></h4>
  <p><%= t('rooms.help.text4') %></p>
  <p><a href="https://github.com/YMGYM">YMGYM(요미)</a>, <a href="https://github.com/idea7654">Idea</a>, Han</p>
  <br />


  <h3><%= t('rooms.help.text5') %></h3>
  <p><%= t('rooms.help.text6') %></p>
  <p><%= t('rooms.help.text7') %></p>

  <br />
  <h3><%= t('rooms.help.text8') %></h3>
  <p><%= t('rooms.help.text9') %></p>
  <p><%= t('rooms.help.text10') %></p>
  <p><%= t('rooms.help.text11') %></p>


  <br />
  <h3><%= t('rooms.help.text12') %></h3>
  <p><%= t('rooms.help.text13') %></p>
  <p><%= t('rooms.help.text14') %></p>
  <p><%= t('rooms.help.text15') %></p>

  <br />
  <h3><%= t('rooms.help.text16') %></h3>
  <p><%= t('rooms.help.text17') %>.</p>
  <p><%= t('rooms.help.text18') %></p>
  <p><%= t('rooms.help.text19') %></p>
  <p><%= t('rooms.help.text20') %></p>
  <p><%= t('rooms.help.text21') %></p>

  <br />
  <h3><%= t('rooms.help.text22') %></h3>
  <p><%= t('rooms.help.text23') %></p>
  <p><%= t('rooms.help.text24') %></p>
  <p><%= t('rooms.help.text25') %></p>
  <p><%= t('rooms.help.text26') %></p>

  <br />
  <h3><%= t('rooms.help.text27') %></h3>
  <p><%= t('rooms.help.text28') %></p>
  <p><%= t('rooms.help.text29') %></p>
  <p><%= t('rooms.help.text30') %></p>
  <p><%= t('rooms.help.text31') %></p>
  <p><%= t('rooms.help.text32') %></p>
</div>

app/views/rooms/main.html.erb
<div class="container-lg center-align">
  <div class="container" style="height: 200px">

  </div>
  <h1>YOMIQUIZ</h1>
  <div class="container" style="height: 50px"></div>
  <p>Made By<br /> 요미귀요미, イデア</p>

  <p>
    <a href="<%= rooms_path %>"><button type="button" class="btn btn-outline-dark btn-lg">Enter</button></a>
  </p>

</div>

app/views/rooms/new.html.erb
<div class="container">
  <div class="row" style="height: 50px"></div>
  <h1><%= t('rooms.new.text1') %></h1>
  <p><%= t('rooms.new.text2') %></p>
  <div class="row" style="height: 50px"></div>
  <%= render 'form' %>
</div>


<script type="text/javascript">
    function openPass() {
        var passInput = document.getElementById('room_password');
          if (passInput.disabled == true){
              passInput.disabled = false;
          }
          else {
              passInput.value = "";
              passInput.disabled = true;

          }
        }
</script>

app/views/rooms/secret.html.erb
<div class="container">
  <div class="row" style="height: 50px"></div>
  <h1><%= t('rooms.secret.text1') %></h1>
  <p><%= t('rooms.secret.text1') %></p>
  <div class="row" style="height: 50px"></div>

  <% if flash.present? %>
    <div class="alert alert-dark" role="alert">
      <%= flash[:alert]%>
    </div>
  <% end %>

  <%= form_tag "/passcheck/#{@room.id.to_s}" do %>
    <%= label_tag :roomPassword, t('rooms.secret.text3') %>
    <%= password_field_tag :roomPassword, nil, class:"form-control" %>

    <%= submit_tag t('rooms.secret.text4'), class: "btn btn-secondary float-right margin-10" %>
  <% end %>

</div>

app/views/rooms/show.html.erb
<div class="container">
  <% if @room.nowPlaying == false %>
    <%= render 'waitroom' %>
  <% else %>
    <%= render 'playingroom' %>
  <%  end %>
</div>