config/routes.rb
Rails.application.routes.draw do
  
  root 'rooms#main'
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    resources :rooms
    devise_for :users

    get '/secret/:id' => 'rooms#secret'
    post '/passcheck/:id' => 'rooms#passCheck'
    post '/search' => 'rooms#search'

    delete '/roomquit' => 'rooms#roomquit'

    get '/chat' => 'chat#index'
    get 'help' => 'rooms#help', as: :help
    post '/startGame' => 'rooms#startGame', as: :startGame

    get '/result/:id/:winner_id' => 'rooms#result', as: :result
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7Z19W9NYJ1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-7Z19W9NYJ1');
    </script>


    <title>요미퀴즈</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload'%>
    <%= javascript_pack_tag 'application' ,'data-turbolinks-track': 'reload'%>
    <% if controller.controller_name == 'rooms' && (controller.action_name == 'index' || controller.action_name == 'show')%>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js" ></script>
    <% end %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= rooms_path %>" data-turbolinks="false">요미퀴즈</a>
      <div>
        <button class="btn btn-dark" id="ko">
          한국어
        </button>
        <button class="btn btn-dark" id="ja">
          日本語
        </button>
      </div>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" href="<%= root_path %>">Home<span class="sr-only">(current)</span></a>
          <a class="nav-link" href="<%= rooms_path %>" data-turbolinks="false">Play</a>
          <% if current_user %>
                <%= link_to 'Logout', destroy_user_session_path,  method: :delete, class: "nav-link" %>
          <% else %>
              <%= link_to 'Login', new_user_session_path,class: "nav-link" %>
          <% end %>
          <a class="nav-link" href="<%= help_path %>" data-turbolinks="false">Help</a>
        </div>
      </div>
      
    </nav>
    <% if flash.present? %>
      <div class="alert alert-dark" role="alert">
        <%= flash[:alert]%>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

<script>
  document.getElementById('ko').addEventListener('click', () => {
    //console.log("작동");
    const path = window.location.pathname.split('/');
    let newStr = "";
    for(let i = 0; i < path.length; i++){
      if(i != 1){
        newStr += path[i] + "/";
      }else{
        newStr += "ko"+"/";
      }
    }

    if(path.length < 3){
      location.href = window.location.protocol + "//" + window.location.host + newStr + 'rooms';
    }else{
      location.href = window.location.protocol + "//" + window.location.host + newStr;
    }
  });

  document.getElementById('ja').addEventListener('click', () => {
    const path = window.location.pathname.split('/');
    let newStr = "";
    for(let i = 0; i < path.length; i++){
      if(i != 1){
        newStr += path[i] + "/";
      }else{
        newStr += "ja"+"/";
      }
    }
    if(path.length < 3){
      location.href = window.location.protocol + "//" + window.location.host + newStr + 'rooms';
    }else{
      location.href = window.location.protocol + "//" + window.location.host + newStr;
    }
  });
</script>